#!/usr/bin/env bash
# Build ABOUT.EXE (Win16 NE, the first-run gesture note) with Open Watcom via tools/watcom.sh.
# The 32x32 16-colour icon is generated by mkico.py and bound with wrc, so Program Manager (and
# tools/grpadd.py, which reads RT_GROUP_ICON out of the executable) has an icon to show.
# Output: guest/about/build/ABOUT.EXE
set -euo pipefail
cd "$(dirname "$0")"; mkdir -p build
python3 mkico.py build/about.ico
cp about.c about.rc build/
W=$(cd ../.. && pwd)/tools/watcom.sh
( cd build && $W wcc -bt=windows -ml -zW -zc -ox -zq -i=/watcom/h -i=/watcom/h/win about.c \
  && { [ -f about.o ] && mv about.o about.obj || true; } \
  && $W wlink system windows name ABOUT.EXE option stack=8192 option heapsize=4096 file about.obj \
       library /watcom/lib286/win/windows.lib libpath /watcom/lib286 libpath /watcom/lib286/win \
  && $W wrc -q -bt=windows -i=/watcom/h -i=/watcom/h/win about.rc ABOUT.EXE )
ls -la build/ABOUT.EXE
